### PR TITLE
Use Rack::Request#url instead of env['REQUEST_URI']

### PR DESCRIPTION
**Pull request by bethesque**
env['REQUEST_URI'] is not populated by all frameworks.

### CODE REVIEW

**Comment by bethesque** [comment]
Can someone review and merge this? I pointed one of my projects at the latest Webmachine codebase and All The Tests failed because REQUEST_URI is not populated. This fixes it, and all the Webmachine tests still pass. @lgierth, I know you reckoned you changed it for a reason, but unless we can work out what that reason was with a failing test, I think we should go ahead with this change.

**Comment by bethesque** [comment]
Oh crap, now I remember why this didn't work in the first place. It fails on the IPv6 tests for Ruby 1.9.3 and rbx-2.

**Comment by Asmod4n** [comment]
I don't quite know why webmachine should have checks if DNS/IP works a okay with adapters. it's their responsibility to handle it. Or do i oversee something here?

**Comment by bethesque** [comment]
I do not know!

I have worked out why REQUEST_URI is populated in the Webmachine tests, and not in mine though. The Webmachine tests start up a server on Webrick which has this line:

```
# webrick/httprequest.rb line 390
      meta["REQUEST_URI"]       = @request_uri.to_s
```
My tests run using Rack::Test, which use only the official Rack vars. 

Haven't worked out why doing `ENV[REQUEST_URI] || rack_req.url` causes the test to break in Travis when `ENV[REQUEST_URI]` doesn't.

**Comment by Asmod4n** [comment]
Ah, that build_uri thing. have you tried to simply use request.url for rack?

**Comment by bethesque** [comment]
Ah! It _is_ failing on master. I didn't make it any worse!

I tried just `rack_req.url`, and then Ruby 1.9.3 and rbx-2 both failed on the IPv6 tests. I changed it to `ENV[REQUEST_URI] || rack_req.url` and then only Ruby 1.9.3 fails.

**Comment by Asmod4n** [comment]
I believe if someone is forced to use ruby 1.9.3 they also don't use IPv6 addresses to connect to their internal services..

**Comment by bethesque** [comment]
If I use `rack_req.url` instead of `env[REQUEST_URI] || rack_req.url`, ruby 1.9.3 fails.
Logging both `env[REQUEST_URI]` and `rack_req.url`, I get this:

```
REQUEST_URI http:/test
rack_req.url http://::1:0/test
```

REQUEST_URI is clearly effed.

To make this pass on 1.9.3, it actually needs the dodgy URI passed into the `Webmachine::Request.new` for some reason...

Still trying to recreate the rbx issue.

**Comment by Asmod4n** [comment]
rack_req.url is also wrong, it needs to be http://[::1]:0/test

**Comment by bethesque** [comment]
Yup. I realised that this test isn't actually passing in the other rubies, it's just not running. They all fail if I enable them, because either the client in the test, or the code under test blows up when it tries to parse `::1` instead of `[::1]` in a URI.

```ruby
  context do
    let(:address) { "::1" }

    it "provides the IPv6 request URI", bethtest: true do
      if RUBY_VERSION =~ /^2\.(0|1)\./
        skip "Net::HTTP regression in Ruby 2.(0|1)"
      end

      request = Net::HTTP::Get.new("/test")
      request["Accept"] = "test/response.request_uri"
      response = client.request(request)
      expect(response.body).to eq("http://[#{address}]:#{port}/test")
    end
  end
```

The only reason it's passing in 1.9.3 is because it's using the dodgy REQUEST_URI "http:/test". I don't know how to fix this, because I don't know if it's possible to identify the host as an IPv6 address from within the build_uri method.

Also, this line confuses me, because it is saying: if the host has no port, return the passed in uri. I'm not sure if this is deliberate or not.

```ruby
    host, _, port = headers.fetch(HOST, "").rpartition(COLON)
    return uri if host.empty?
```

I putsed out all the uris that came into build_uri, and I get these different combinations:

http:/test
http://localhost/
http://localhost:8080/
http://localhost:8080/notes
http://127.0.0.1:63431/test

If we changed all the adapters to pass in the path instead of the full URL we might be able to do it, because then we can manually construct the URL. I haven't been able to get a working testcase with IPv6 though, because the HTTP::Net client blows up.

**Comment by Asmod4n** [comment]
Net::HTTP never was able to handle IPv6 addresses when handed over in Net::HTTP.new(addr, port)
It can handle them with Net::HTTP.get(URI("http://[addr]:port"))

**Comment by Asmod4n** [comment]
@bethesque fixed it in my PR #213 build_uri was broken and so were the IPv6 tests.

**Comment by bethesque** [comment]
I'd come to that conclusion! I thought I was going crazy for a little while, trying to make sense of it all. Thanks.

**Pull request closed without merging**
